### ISSUE TITLE
the datasetfile is not exist

### ISSUE THREAD

**Issue by Lx1010** [rainmilk/ijcai18mlma#1]
hi，i try run this project，but it is not exit glove.6B.%dd.txt file in preprocessMovieLens.py
specifically，the path /data/MovieLens/ is no files about glove.6B.200d.txt

**Comment by Lx1010** [comment]
sorry，I didn't run file preprocessMovieLens.py up front

**Comment by Lx1010** [comment]
i had download from web-site

**Comment by rainmilk** [comment]
Refer to the repro steps.
